---
- block:
  - name: install getty@tty1.service.d directory
    file:
      path: /etc/systemd/system/getty@tty1.service.d
      state: directory
      mode: 0755

  - name: install autologin.conf
    copy:
      src: autologin.conf
      dest: /etc/systemd/system/getty@tty1.service.d/
      mode: 0644

  become: true
