---
- name: install firefox package
  become: true
  package:
    name: firefox
    state: present

- name: find default firefox user profile
  find:
    paths: ~/.mozilla/firefox/
    pattern: "*.default-release"
    file_type: directory
    recurse: no
  register: firefox_profile_find_result

- name: print warning if firefox profile is not yet present
  debug:
    msg: Firefox profile is not present, rerun after starting Firefox
  when: firefox_profile_find_result.matched <= 0

- name: install user.js file
  template:
    src: user.js
    dest: "{{ firefox_profile_find_result.files[0].path }}/"
    mode: 0755
  # notify:
  #   - remove firefox prefs file
  when: firefox_profile_find_result.matched > 0

- name: install firefox profile chrome directory
  file:
    path: "{{ firefox_profile_find_result.files[0].path }}/chrome/"
    state: directory
    recurse: true
    mode: 0755
  when: firefox_profile_find_result.matched > 0

- name: install firefox profile chrome file
  copy:
    src: userChrome.css
    dest: "{{ firefox_profile_find_result.files[0].path }}/chrome/"
    mode: 0755
  when: firefox_profile_find_result.matched > 0
