---
- name: install firefox package
  become: true
  package:
    name: firefox
    state: present

- name: install user firefox configuration directories
  file:
    path: ~/.mozilla/firefox/km66udzy.profile-release
    state: directory
    recurse: true
    mode: 0755

- name: install user firefox profiles configuration
  copy:
    src: profiles.ini
    dest: ~/.mozilla/firefox/
    mode: 0444

- name: install user.js file
  template:
    src: user.js
    dest: ~/.mozilla/firefox/km66udzy.profile-release/user.js
    mode: 0755
  # notify:
  #   - remove firefox prefs file

- name: install firefox profile chrome directory
  file:
    path: ~/.mozilla/firefox/km66udzy.profile-release/chrome/
    state: directory
    recurse: true
    mode: 0755

- name: install firefox profile chrome file
  copy:
    src: userChrome.css
    dest: ~/.mozilla/firefox/km66udzy.profile-release/chrome/
    mode: 0755
