---
- block:
  - name: install wired network configuration
    copy:
      src: 20-wired.network
      dest: /etc/systemd/network/
      mode: 0644
    notify:
      - restart systemd-networkd service

  - name: install systemd-networkd service
    service:
      name: systemd-networkd
      state: started
      enabled: true

  become: yes

- block:
  - name: install wireless network configuration
    copy:
      src: 25-wireless.network
      dest: /etc/systemd/network/
      mode: 0644
    notify:
      - restart systemd-networkd service

  - name: install wpa_supplicant package
    package:
      name: wpa_supplicant
      state: present

  - name: install wpa_supplicant adapter config
    copy:
      src: wpa_supplicant.conf
      dest: "/etc/wpa_supplicant/wpa_supplicant-{{ systemd_networkd_wireless }}.conf"
      force: false
      mode: 0644

  - name: install wpa_supplicant adapter service
    service:
      name: "wpa_supplicant@{{ systemd_networkd_wireless }}"
      state: started
      enabled: true

  when: systemd_networkd_wireless is defined
  become: yes
