---
- block:
  - name: install intel graphics packages
    package:
      name:
        - mesa
        - xf86-video-intel
        - libva-intel-driver
      state: present

  - name: install intel graphics driver options
    copy:
      src: i915.conf
      dest: /etc/modprobe.d/
      mode: 0644

  become: true

