---
- name: install ncmpcpp packages
  package:
    name:
      - ncmpcpp
      - mpc
    state: present
  become: true

- name: install ncmpcpp config directory
  file:
    path: ~/.config/ncmpcpp
    state: directory
    recurse: true
    mode: 0755

- name: install ncmpcpp config file
  copy:
    src: config
    dest: ~/.config/ncmpcpp/
    mode: 0755
