---
- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
    - vars/rho.yml
  roles:
    - common_base
    - graphics_nvidia
    - common_desktop_X11
    - xrandr
    - common_applications
    - mpd
    - ncmpcpp
