---
- name: install windows terminal
  community.windows.win_scoop:
    name: windows-terminal

- name: install windows terminal configuration
  win_copy:
    src: settings.json
    dest: "{{ ansible_facts['user_dir'] }}\\AppData\\Local\\Microsoft\\Windows Terminal\\"
  # Windows Terminal autoupdates config instead of having layered configs
  # so it will always be marked as changed otherwise
  changed_when: false
