---
- block:
  - name: install tridactyl extension
    package:
      name: firefox-tridactyl
      state: present

  - name: install tridactyl native extension
    aur:
      name: firefox-tridactyl-native

  become: yes

- name: install tridactyl config
  copy:
    src: tridactylrc
    dest: ~/.config/tridactyl/
    mode: 0644
