---
- name: "install cryfs base directory [{{ item.name }}]"
  file:
    path: "~/.cryfs/{{ item.name }}/base"
    state: directory
    mode: 0700

- name: "install cryfs mount directory [{{ item.name }}]"
  file:
    path: "~/.cryfs/{{ item.name }}/mount"
    state: directory
    mode: 0700

- name: "install cryfs mount symlink [{{ item.name }}]"
  file:
    src: "~/.cryfs/{{ item.name }}/mount"
    dest: "{{ item.mount }}"
    state: link
    mode: 0700

- name: "install cryfs encryption key [{{ item.name }}]"
  copy:
    content: "{{ item.key }}"
    dest: "~/.cryfs/{{ item.name }}/key"
    mode: 0600
