---
- name: "install cryfs base directory [{{ item.name }}]"
  file:
    path: "~/.cryfs/{{ item.name }}/base"
    state: directory
    mode: 0700

- name: "install cryfs directory key [{{ item.name }}]"
  copy:
    content: "{{ item.key }}"
    dest: "~/.cryfs/{{ item.name }}/key"
    mode: 0600

- name: install cryfs mount directory [{{ item.mount }}]
  file:
    path: "{{ item.mount }}"
    state: directory
    mode: 0700
