---
- block:
  - name: install cryfs packages
    aura:
      name: cryfs

  - name: install cryfs exec wrapper script
    copy:
      src: cryfs-mount
      dest: /usr/local/bin/
      mode: 0755

  - name: install cryfs systemd user unit
    copy:
      src: cryfs@.service
      dest: /etc/systemd/user/
      mode: 0755
    notify:
      - reload systemctl user daemon

  become: true

- meta: flush_handlers

- name: stop all cryfs systemd services (fuse mounts can cause havoc with directory setups)
  systemd:
    name: cryfs@*
    state: stopped
    user: true
  # Must exist is missing or something
  # See: https://github.com/ansible/ansible/issues/16134
  ignore_errors: yes

- name: install cryfs base directory
  file:
    path: ~/.cryfs
    state: directory
    mode: 0700

- include_tasks: directory.yml
  with_items: "{{ cryfs }}"
