---
- block:
  - name: install compton package
    package:
      name: compton
      state: present

  - name: install compton user service unit
    copy:
      src: compton.service
      dest: /etc/systemd/user/
      mode: 0644

  become: true

- name: install compton configuration
  copy:
    src: compton.conf
    dest: ~/.config/
    mode: 0444

# Don't start service automatically, as it may fail before system is restarted
# during initial setup.
- name: install compton user service
  systemd:
    name: compton
    scope: user
    enabled: true
    daemon_reload: yes
