---
- block:
  - name: install compton package
    package:
      name: compton
      state: present

  - name: install compton user service unit
    copy:
      src: compton.service
      dest: /etc/systemd/user/
      mode: 0644
    notify: reload systemd user daemon

  become: true

- meta: flush_handlers

- name: install compton user service
  systemd:
    name: compton
    scope: user
    enabled: true
