---
- name: install feh package
  become: true
  package:
    name: feh
    state: present

- name: install feh configuration directory
  file:
    path: ~/.config/feh
    state: directory
    mode: 0755

- name: install feh themes
  copy:
    src: themes
    dest: ~/.config/feh/
    mode: 0444
