---
- block:
  - name: install tlp package
    package:
      name: tlp
      state: present

  - name: install tlp configuration
    copy:
      src: tlp/tlp
      dest: /etc/default/tlp
      mode: 0644

  - name: install tlp service
    service:
      name: tlp
      state: started
      enabled: true

  - name: install tlp-sleep service
    service:
      name: tlp-sleep
      enabled: true

  become: true
