---
- block:
  - name: install mtrack package
    aura:
      name: xf86-input-mtrack-git
      state: present

  - name: install mtrack configuration
    copy:
      src: touchpad/01-mtrack-touchpad.conf
      dest: /etc/X11/xorg.conf.d/
      mode: 0644

  # Install dispad manually from AUR Archive
  # https://raw.githubusercontent.com/aur-archive/dispad-git/master/PKGBUILD
  become: true

- name: install user dispad configuration directory
  file:
    path: ~/.config/dispad
    state: directory
    mode: 0700

- name: install user dispad configuration file
  copy:
    src: touchpad/dispad.conf
    dest: ~/.config/dispad/
    mode: 0600

- name: install user dispad xprofile start script
  copy:
    src: touchpad/xprofile.d/dispad
    dest: ~/.xprofile.d/dispad
    mode: 0500
