---
- name: install firefox package
  become: true
  package:
    name: firefox
    state: present

- name: install user firefox configuration directories
  file:
    path: ~/.mozilla/firefox/profile
    state: directory
    recurse: true
    mode: 0700

- name: install user firefox profiles configuration
  copy:
    src: firefox/profiles.ini
    dest: ~/.mozilla/firefox/
    mode: 0644

- name: install user.js file
  template:
    src: firefox/user.js
    dest: ~/.mozilla/firefox/profile/user.js
    mode: 0700
  when: not ansible_check_mode
  notify:
    - remove firefox prefs file
