---
- name: install firefox package
  become: true
  package:
    name: firefox
    state: present

- name: install user firefox configuration directories
  file:
    path: ~/.mozilla/firefox/profile
    state: directory
    recurse: true
    mode: 0700

- name: install user firefox profiles configuration
  copy:
    src: firefox/profiles.ini
    dest: ~/.mozilla/firefox/
    mode: 0644

  # TODO: Was piping output into user.js file directly, but then I cannot run through
  # a template.
- name: generate user.js file content
  script: firefox/generate-user.js.sh
  # register: firefox_user_js
  changed_when: false

- name: install user.js file
  template:
  # copy:
    # content: "{{ firefox_user_js.stdout }}"
    src: /tmp/user.js
    dest: ~/.mozilla/firefox/profile/user.js
    mode: 0700
  when: not ansible_check_mode
  notify:
    - remove firefox prefs file
