---
- name: restart mpd service
  systemd:
    name: mpd
    user: true
    state: restarted

- name: reload systemd user daemon
  shell: systemctl --user daemon-reload

- name: reload systemd daemon
  shell: systemctl daemon-reload
  become: true
