---
- block:
  - name: install network manager packages
    package:
      name:
        - broadcom-wl-dkms
        - networkmanager
        - network-manager-applet
        - dhclient
        # Needed to store Wi-Fi passwords
        - gnome-keyring
      state: present

  # Must ensure dhcpcd is disabled as network manager uses dhclient
  - name: uninstall dhcpcd service
    service:
      name: dhcpcd
      state: stopped
      enabled: false

  - name: install NetworkManager service
    service:
      name: NetworkManager
      state: started
      enabled: true

  become: true
