---
- name: install gtk package
  become: true
  package:
    name: gtk-engines
    state: present

- name: install user gtk3 configuration directory
  file:
    path: ~/.config/gtk-3.0
    state: directory
    mode: 0755

- name: install user gtk3 configuration
  template:
    src: settings.ini
    dest: ~/.config/gtk-3.0/
    mode: 0444

- name: install user gtk2 configuration
  template:
    src: gtkrc-2.0
    dest: ~/.gtkrc-2.0
    mode: 0444
