---
- block:
  - name: install pcmanfm package
    package:
      name: pcmanfm-gtk3
      state: present

  - name: install pcmanfm user service unit
    copy:
      src: pcmanfm.service
      dest: /etc/systemd/user/
      mode: 0644

  become: true

- name: install user pcmanfm configuration directories
  file:
    path: ~/.config/pcmanfm/default
    state: directory
    recurse: true
    mode: 0755

- name: install user pcmanfm configuration
  copy:
    src: pcmanfm.conf
    dest: ~/.config/pcmanfm/default/
    mode: 0755

- name: install pcmanfm user service
  systemd:
    name: pcmanfm
    scope: user
    enabled: true
    daemon_reload: yes
