---
- name: install pass package
  package:
    name: pass
    state: present
  become: true

- name: install pass env vars
  template:
    src: bashrc.d/PASSWORD_STORE_
    dest: ~/.bashrc.d/environment/
    mode: 0600

- name: install pass directory
  file:
    path: "{{ pass_store_directory }}"
    state: directory
    mode: 0700
    recurse: true
