---
- block:
  - name: force remove freetype and related packages
    pacman:
      name: "{{ item }}"
      state: absent
      force: yes
    with_items:
      - freetype2
      - fontconfig
      - cairo

  - name: install infinality packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - ttf-hack
      - freetype2-infinality-ultimate
      - fontconfig-infinality-ultimate
      - cairo-infinality-ultimate
      - ibfonts-meta-extended

  - name: get infinality font presets
    shell: /usr/bin/fc-presets check | grep -oP '(?<=seems to be \[ ).*(?= \])'
    register: current_font_config
    failed_when: current_font_config.rc == 2
    changed_when: false

  - name: set infinality font presets
    shell: echo 1 | /usr/bin/fc-presets set
    when: not ansible_check_mode and current_font_config.stdout != "combi"

  - name: install hack font config
    copy:
      src: 60-latin-combi.conf
      dest: /etc/fonts/conf.avail.infinality/combi/
      mode: 0644

  become: true
