---
- name: install kitty package
  become: true
  package:
    name: kitty
    state: present

- name: install user kitty directory
  file:
    path: ~/.config/kitty
    state: directory
    mode: 0755

- name: install user kitty configuration
  template:
    src: kitty.conf
    dest: ~/.config/kitty/
    mode: 0444
