---
- name: install user pacman configuration directory
  file:
    path: ~/.config/pacman
    state: directory
    mode: 0700

- name: install user makepkg configuration
  copy:
    src: makepkg.conf
    dest: ~/.config/pacman/
    mode: 0600
