---
- block:
  - name: install i3 packages
    package:
      name:
        - i3-wm
        - i3status
      state: present

  become: true

- name: install user i3 configuration directories
  file:
    path: "~/.config/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - i3
    - i3status

- name: install user i3 configuration
  template:
    src: "{{ item }}"
    dest: "~/.config/{{ item }}"
    mode: 0444
  with_items:
    - i3/config
    - i3status/config

- name: install user i3status shell scripts
  copy:
    src: "{{ item }}"
    dest: "~/.config/i3/{{ item }}"
    mode: 0544
  with_items:
    - i3statuswrap.sh
    - mem.sh
