---
- block:
  - name: install mbpfan package
    aur:
      name: mbpfan-git

  - name: install mbpfan configuration
    copy:
      src: mbpfan.conf
      dest: /etc/
      mode: 0644

  - name: install mbpfan service
    service:
      name: mbpfan
      state: started
      enabled: true

  become: true

