---
- name: install linux ripgrep package
  package:
    name: ripgrep
    state: present
  become: true
  when: "ansible_facts['os_family']|lower != 'windows'"

- name: install windows ripgrep package
  community.windows.win_scoop:
    name: ripgrep
  when: "ansible_facts['os_family']|lower == 'windows'"
