---
- name: install fzf package
  package:
    name: fzf
    state: present
  become: true

- name: install fzf bash completions and shortcuts
  copy:
    src: bashrc.d/fzf
    dest: ~/.bashrc.d/
    mode: 0600

- name: install fzf environment variables
  copy:
    src: bashrc.d/environment/FZF_DEFAULT_COMMAND
    dest: ~/.bashrc.d/environment/
    mode: 0600
