- name: install fzf package
  community.windows.win_scoop:
    name: fzf

- name: install FZF_DEFAULT_COMMAND user environment variable
  win_environment:
    name: FZF_DEFAULT_COMMAND
    value: "{{ fzf_default_command }}"
    level: user
