---
- block:
  - name: install xf86-input-libinput package
    package:
      name: xf86-input-libinput

  - name: install libinput touchpad configuration
    copy:
      src: 02-libinput-touchpad.conf
      dest: /etc/X11/xorg.conf.d/
      mode: 0644

  - name: add user to input group
    user:
      name: "{{ lookup('env', 'USER') }}"
      groups: input
      append: true

  become: true
