---
- name: install linux git package
  package:
    name: git
    state: present
  become: yes
  when: "ansible_facts['os_family']|lower != 'windows'"

- name: install windows git package
  win_scoop:
    name: git
    state: present
  when: "ansible_facts['os_family']|lower == 'windows'"

- name: install user git configuration directory
  file:
    path: "{{ git__config_path_linux }}"
    state: directory
    mode: 0755
  when: "ansible_facts['os_family']|lower != 'windows'"

- name: install user git configuration
  template:
    src: config
    dest: "{{ git__config_dest }}"
    mode: 0444

- name: install GIT_SSH user environment variable
  win_environment:
    name: GIT_SSH
    level: user
    value: C:\Windows\System32\OpenSSH\ssh.exe
  when: "ansible_facts['os_family']|lower == 'windows'"
