---
- name: install git package
  become: true
  package:
    name: git
    state: present

- name: install user git configuration directory
  file:
    path: ~/.config/git
    state: directory
    mode: 0700

- name: install user git configuration
  template:
    src: config
    dest: ~/.config/git/
    mode: 0600
