#!/bin/sh
directory=~/.xprofile.d

if [[ -d "${directory}" && -r "${directory}" && -x "${directory}" ]]; then
	for file in "${directory}"/* ; do
		[[ -f "${file}" && -r "${file}" ]] && . "${file}"
	done
	unset file
fi

unset directory
