---
- name: install atom package
  aur:
    name: atom-editor-bin
  become: true

- name: install apm packages
  apm:
    name: "{{ item }}"
  with_items:
    - nucleus-dark-ui
    - docblockr
    - editorconfig
    - highlight-selected
    - indent-guide-improved
    - language-ansible
    - language-docker
    - language-ini
    - language-ledger
    - language-nginx
    - language-nunjucks
    - language-terraform
    - linter
    - linter-eslint
    - pigments
    - minimap
    - minimap-pigments
    - minimap-highlight-selected
    - minimap-find-and-replace
    - minimap-selection
    - minimap-linter
    - synced-sidebar
    - Stylus
    - auto-detect-indentation

# - name: install apm hidpi package
#   apm:
#     name: hidpi
#   when: ansible_hostname == "wasat"

- name: install atom config
  template:
    src: config.cson
    dest: ~/.atom/
    mode: 0644

- name: install atom styles
  copy:
    src: styles.less
    dest: ~/.atom/
    mode: 0644
