---
- name: install atom package
  aura:
    name: atom-editor-bin
    state: present
  become: true

- name: install apm packages
  apm:
    name: "{{ item }}"
  with_items:
    - nucleus-dark-ui
    - docblockr
    - editorconfig
    - highlight-selected
    - indent-guide-improved
    - language-ansible
    - language-docker
    - language-ini
    - language-ledger
    - language-nginx
    - language-nunjucks
    - language-terraform
    - linter
    - linter-eslint
    - pigments
    - minimap
    - minimap-pigments
    - minimap-highlight-selected
    - minimap-find-and-replace
    - minimap-selection
    - minimap-linter
    - synced-sidebar
    - linter
    - linter-eslint
    - Stylus
    - auto-detect-indentation

- name: install apm hidpi package
  apm:
    name: hidpi
  when: ansible_hostname == "wasat"

- name: install atom configs
  copy:
    src: "{{ item }}"
    dest: ~/.atom/
    mode: 0644
  with_items:
    - config.cson
    - styles.less
