---
# Disable installing until fix for https://github.com/PowerShell/PowerShell/issues/11314
# Just manually installing appx for now
# - name: install powershell
#   win_scoop:
#     name: pwsh

- name: inspect PSGallery repository trusted status
  win_command: pwsh.exe -NoProfile -Command -
  args:
    stdin: (Get-PSRepository -Name PSGallery).InstallationPolicy
  register: powershell_psgallery_trusted_result
  changed_when: false

- name: set PSGallery repository trusted status
  win_command: pwsh.exe -NoProfile -Command -
  args:
    stdin: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
  when: not ansible_check_mode and powershell_psgallery_trusted_result.stdout is search("Untrusted")

- name: inspect PSFzf module status
  win_command: pwsh.exe -NoProfile -Command -
  args:
    stdin: Get-Module -ListAvailable -Name PSFzf
  register: powershell_module_psfzf_result
  changed_when: false

- name: install PSFzf module
  win_command: pwsh.exe -NoProfile -Command -
  args:
    stdin: Install-Module -Name PSFzf
  when: not ansible_check_mode and powershell_module_psfzf_result.stdout == ""

- name: install powershell all hosts profile
  win_copy:
    src: profile.ps1
    dest: ~\Documents\PowerShell\
