---
- name: install terminator package
  become: true
  package:
    name: terminator
    state: present

- name: install user terminator configuration directory
  file:
    path: ~/.config/terminator
    state: directory
    mode: 0755

- name: install user terminator configuration
  template:
    src: config
    dest: ~/.config/terminator/
    mode: 0444
