---
- block:
  - name: install yubikey smartcard dependency packages
    package:
      name:
        - libusb-compat
      state: present

    # Add udev rules for permissions on smartcard for yubikey
    # This config also fixes a bug related to scdaemon not working when
    # replugging the key, so the workaround for now is have udev kill
    # scdaemon on plug.
    # https://bugs.gnupg.org/gnupg/issue2167
  - name: install udev smartcard rules
    copy:
      src: yubikey.rules
      dest: /etc/udev/rules.d/
      mode: 0644

  - name: install scdaemon hibernate resume restart service unit
    copy:
      src: scdaemon-hibernateresume.service
      dest: /etc/systemd/system/
      mode: 0644
    notify: reload systemd daemon

  - meta: flush_handlers

  - name: install scdaemon hibernate resume restart service
    service:
      name: scdaemon-hibernateresume.service
      enabled: true

  become: true
