---
- name: install rofi package
  become: true
  package:
    name: rofi
    state: present

- name: install user rofi configuration directory
  file:
    path: ~/.config/rofi
    state: directory
    mode: 0700

- name: install user rofi configuration
  template:
    src: config
    dest: ~/.config/rofi/
    mode: 0600
