---
- name: install rofi package
  become: true
  package:
    name: rofi
    state: present

- name: install rofi configuration directory
  file:
    path: ~/.config/rofi
    state: directory
    mode: 0755

- name: install rofi theme
  copy:
    src: purple.rasi
    dest: ~/.config/rofi/
    mode: 0444

- name: install rofi configuration
  template:
    src: config.rasi
    dest: ~/.config/rofi/
    mode: 0444
