---
- block:
  - name: install alhena music mount unit
    copy:
      src: mnt-alhena-music.mount
      dest: /etc/systemd/system/
      mode: 0755
    notify:
      - reload systemd daemon

  - meta: flush_handlers

  - name: enable alhena music mount unit
    systemd:
      name: mnt-alhena-music.mount
      state: started
      enabled: true

  become: true

- name: install mpd package
  package:
    name: mpd
    state: present
  become: true

- name: install mpd config directory
  file:
    path: ~/.config/mpd
    state: directory
    recurse: true
    mode: 0700

- name: install mpd config file
  copy:
    src: mpd.conf
    dest: ~/.config/mpd/
    mode: 0700
  notify:
    - restart mpd service

- name: install mpd drop in unit directory
  file:
    path: ~/.config/systemd/user/mpd.service.d
    state: directory
    recurse: true
    mode: 0755

- name: install mpd drop in unit
  copy:
    src: mpd.service.d/10-mpd-share-dependency.conf
    dest: ~/.config/systemd/user/mpd.service.d
    mode: 0755
  notify:
    - reload systemd user daemon
    - restart mpd service

- meta: flush_handlers

- name: install mpd service
  systemd:
    name: mpd
    user: true
    state: started
    enabled: true
