---
- block:
  - name: install share music mount unit
    copy:
      src: "{{ item }}"
      dest: /etc/systemd/system/
      mode: 0644
    with_items:
      - mnt-share-music.mount
      - mnt-share-music.automount

  - name: enable share music automount unit
    systemd:
      name: mnt-share-music.automount
      state: started
      enabled: yes
      daemon_reload: yes

  - name: install mpd package
    package:
      name: mpd
      state: present

  become: true

- name: install mpd config directory
  file:
    path: ~/.config/mpd
    state: directory
    recurse: true
    mode: 0755

- name: install mpd playlist directory
  file:
    path: ~/.config/mpd/playlists
    state: directory
    recurse: true
    mode: 0755

- name: install mpd config file
  copy:
    src: mpd.conf
    dest: ~/.config/mpd/
    mode: 0755
  notify:
    - restart mpd service

- block:
  - name: install mpd drop in unit directory
    file:
      path: /etc/systemd/user/mpd.service.d
      state: directory
      recurse: true
      mode: 0755

  - name: install mpd drop in unit
    copy:
      src: mpd.service.d/10-mpd-share-dependency.conf
      dest: /etc/systemd/user/mpd.service.d/
      mode: 0644
    notify:
      - restart mpd service

  become: yes

- name: install mpd service
  systemd:
    name: mpd
    scope: user
    state: started
    enabled: yes
    daemon_reload: yes
