---
- block:
  # Install file directly instead of using localectl as
  # it checks for X11 running now, which will mess up initial config
  - name: install keyboard layout config
    template:
      src: 00-keyboard.conf
      dest: /etc/X11/xorg.conf.d/
      mode: 0644

  - name: install xcape
    package:
        name: xcape
        state: present

  - name: install togglecapsctrl script
    template:
      src: togglecapsctrl
      dest: /usr/local/bin/
      mode: 0755

  become: true
