---
- block:
  - name: get X11 keymap settings
    shell: "/usr/bin/localectl status | grep -oP '(?<=X11 Variant: ).*'"
    register: current_X11_keyboard_variant
    failed_when: current_X11_keyboard_variant.rc == 2
    changed_when: false

  - name: set X11 keymap settings
    command: "/usr/bin/localectl --no-convert set-x11-keymap us pc105 {{ keyboard_layout }}"
    when: not ansible_check_mode and current_X11_keyboard_variant.stdout != keyboard_layout

  - name: install xcape
    package:
        name: xcape
        state: present

  - name: install togglecapsctrl script
    template:
      src: togglecapsctrl
      dest: /usr/local/bin/
      mode: 0755

  become: true
