---
- block:
  - name: install X11 packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - xorg-server
      - xorg-server-utils

  - name: install X11 display size configuration
    template:
      src: 90-monitor-scale.conf
      dest: /etc/X11/xorg.conf.d/
      mode: 0644
    when: X11_display_size is defined

  become: true

- import_tasks: keyboard.yml
- import_tasks: mouse.yml
