---
- block:
  - name: install X11 packages
    package:
      name:
        - xorg-server
        - xorg-xinit
        - xorg-xinput
        - xorg-xrandr
        - xorg-xrdb
        - hsetroot
      state: present

  - name: install X11 display size configuration
    template:
      src: 90-monitor-scale.conf
      dest: /etc/X11/xorg.conf.d/
      mode: 0644
    when: X11_display_size is defined

  - name: install systemd user xsession target
    copy:
      src: xsession.target
      dest: /etc/systemd/user/
      mode: 0644
    notify: reload systemd user daemon

  - meta: flush_handlers

  become: true

- name: install .xprofile.d directory
  file:
    path: ~/.xprofile.d
    state: directory
    mode: 0755

- name: install .xprofile file
  copy:
    src: xprofile
    dest: ~/.xprofile
    mode: 0744

- name: install Xresources
  template:
    src: Xresources
    dest: ~/.Xresources
    mode: 0444

- name: install .xinitrc file
  copy:
    src: xinitrc
    dest: ~/.xinitrc
    mode: 0444

- import_tasks: mouse.yml

