---
- block:
  - name: install font packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - freetype2
      - fontconfig
      - cairo
      - ttf-hack
      - ttf-liberation
      - ttf-ubuntu-font-family
      - ttf-dejavu

  - name: install aura font packages
    aura:
      name: "{{ item }}"
      state: present
    with_items:
      - otf-fira-code

  - name: install user font config
    copy:
      src: 91-user-config.conf
      dest: /etc/fonts/conf.avail/
      mode: 0644

  - name: install active font configurations
    file:
      src: "/etc/fonts/conf.avail/{{ item }}"
      dest: "/etc/fonts/conf.d/{{ item }}"
      state: link
    with_items:
      - 11-lcdfilter-default.conf
      - 10-sub-pixel-rgb.conf
      - 10-hinting-slight.conf
      - 91-user-config.conf

  become: true
