---
- block:
  - name: install lightdm packages
    package:
      name:
        - lightdm
        - lightdm-gtk-greeter
      state: present

  - name: enable lightdm service
    service:
      name: lightdm
      enabled: true

  become: true
