---
- block:
  - name: install smartcard packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - pcsclite
      - libusb-compat

  - name: enable pcscd service
    service:
      name: pcscd
      enabled: true

  # Add udev rules for permissions on smartcard for yubikey
  # This config also fixes a bug related to scdaemon not working when
  # replugging the key, so the workaround for now is have udev kill
  # scdaemon on plug.
  # https://bugs.gnupg.org/gnupg/issue2167
  - name: install udev smartcard reset rule
    copy:
      src: smartcard/smartcard_reset.rules
      dest: /etc/udev/rules.d/smartcard_reset.rules
      mode: 0644

  become: yes
