if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
	unset SSH_AGENT_PID
	if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
		export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
	fi
	exec sway
fi

[[ -f ~/.bashrc ]] && . ~/.bashrc
