---
gpg__program_path_windows: "{{ ansible_facts['user_dir'] }}\\scoop\\apps\\gpg\\current\\bin\\gpg.exe"

gpg__config_path_linux: ~/.gnupg/
gpg__config_path_windows: "{{ ansible_facts['user_dir'] }}\\scoop\\persist\\gpg\\home\\"
gpg__config_path: "{{ lookup('vars', 'gpg__config_path_' + ansible_facts['os_family']|lower, default=gpg__config_path_linux) }}"
