---
- block:
  - name: install systemd-timesyncd configuration
    copy:
      src: systemd_timesyncd/timesyncd.conf
      dest: /etc/systemd/
      mode: 0644
    notify:
      - restart systemd_timesyncd service

  - name: install systemd-timesyncd service
    service:
      name: systemd-timesyncd
      state: started
      enabled: true

  become: yes
