---
- name: install syncthing package
  become: true
  package:
    name: syncthing
    state: present

- name: install syncthing service
  systemd:
    name: syncthing
    scope: user
    state: started
    enabled: true
