#!/bin/bash
mount() {
	/usr/bin/cryfs -f "$2/base" "$2/mount" < "$2/key"
}

umount() {
	/usr/bin/fusermount -uz "$2/mount"
}

usage () {
	echo "Usage: $0 {mount|umount} directory"
	exit 1
}

if [ -z "$2" ]; then
	echo 'Must pass a cryfs configuration directory'
	usage
fi

if [ ! -d "$2" ] || [ ! -d "$2/base" ] || [ ! -d "$2/mount" ] || [ ! -f "$2/key" ]; then
	echo "[$2] is not a valid cryfs configuration directory"
	usage
fi

case "$1" in
	mount)
		mount $@
		;;
	umount)
		umount $@
		;;
	*)
		usage
esac
