---
- name: install neovim packages
  package:
    name:
      - neovim
      - python-pynvim
      - editorconfig-core-c
  become: true

- name: get neovim config directory
  command: "{{ neovim_config_directory_command }}"
  register: neovim_config_cmd
  check_mode: no
  changed_when: false

- name: set neovim config directory var
  set_fact:
    neovim_config_directory: "{{ neovim_config_cmd.stderr }}/"


- name: install vim alias
  copy:
    src: bashrc.d/aliases/vim
    dest: ~/.bashrc.d/aliases/
    mode: 0444
