---
# install from aur until 0.5 release
- name: install neovim git package
  aur:
    name: neovim-git
  become: true

- name: install neovim packages
  package:
    name:
      # - neovim
      - python-pynvim
      - editorconfig-core-c
  become: true

- name: install paq-nvim plugin
  git:
    repo: https://github.com/savq/paq-nvim.git
    dest: ~/.local/share/nvim/site/pack/paqs/opt/paq-nvim
    update: no

- name: install neovim config
  copy:
    src: init.vim
    dest: ~/.config/nvim/
    mode: 0444

- name: install neovim lua config
  copy:
    src: lua/init.lua
    dest: ~/.config/nvim/lua/
    mode: 0444
    directory_mode: 0755

- name: install vim alias
  copy:
    src: bashrc.d/aliases/vim
    dest: ~/.bashrc.d/aliases/
    mode: 0444
