---
- block:
  - name: install neovim package
    package:
      name: neovim
      state: present

  - name: install editorconfig-core-c package
    package:
        name: editorconfig-core-c
        state: present

  become: true

- name: install vim alias
  copy:
    src: bashrc.d/aliases/vim
    dest: ~/.bashrc.d/aliases/
    mode: 0600
