---
- block:
  - name: install neovim package
    package:
      name: neovim
      state: present

  - name: install editorconfig-core-c package
    package:
        name: editorconfig-core-c
        state: present

  become: true

- name: install vim alias
  copy:
    src: bashrc.d/aliases/vim
    dest: ~/.bashrc.d/aliases/
    mode: 0600

- name: install minpac plugin
  git:
    repo: https://github.com/k-takata/minpac.git
    dest: ~/.config/nvim/pack/minpac/opt/minpac
    update: no

- name: install neovim config
  copy:
    src: init.vim
    dest: ~/.config/nvim/
    mode: 0600
