---
- name: install scoop versions bucket
  community.windows.win_scoop_bucket:
    name: versions
    state: present

- name: install neovim packages
  community.windows.win_scoop:
    name:
      - neovim-nightly
      - editorconfig
      - fvim

- name: get neovim config directory
  win_command: "{{ neovim_config_directory_command }}"
  register: neovim_config_cmd
  check_mode: no
  changed_when: false

- name: set neovim config directory var
  set_fact:
    neovim_config_directory: "{{ neovim_config_cmd.stderr }}/"

- name: install neovim graphical config
  copy:
    src: "{{ item }}"
    dest: "{{ neovim_config_directory }}"
  loop:
    - ginit.vim

- name: install vim alias
  win_copy:
    src: 10-alias_vim_nvim.ps1
    dest: ~\Documents\PowerShell\profile.d\
