---
- name: install scoop versions bucket
  community.windows.win_scoop_bucket:
    name: versions
    state: present

- name: install neovim packages
  community.windows.win_scoop:
    name:
      - neovim-nightly
      - editorconfig
      - fvim

- name: install neovim configuration directory
  win_file:
    path: ~\AppData\Local\nvim
    state: directory

- name: install paq-nvim directory
  win_file:
    path: ~\AppData\Local\nvim-data\site\pack\paqs\opt
    state: directory

- name: install paq-nvim plugin
  win_command: pwsh.exe -NoProfile -Command -
  args:
    stdin: "git clone https://github.com/savq/paq-nvim.git {{ ansible_facts['user_dir'] }}\\AppData\\Local\\nvim-data\\site\\pack\\paqs\\opt\\paq-nvim"
    creates: "{{ ansible_facts['user_dir'] }}\\AppData\\Local\\nvim-data\\site\\pack\\paqs\\opt\\paq-nvim"

- name: install neovim configs
  copy:
    src: "{{ item }}"
    dest: ~\AppData\Local\nvim\
  loop:
    - init.vim
    - ginit.vim

- name: install neovim lua config
  copy:
    src: lua/init.lua
    dest: ~\AppData\Local\nvim\lua\

- name: install vim alias
  win_copy:
    src: 10-alias_vim_nvim.ps1
    dest: ~\Documents\PowerShell\profile.d\
