---
- block:
  - name: install nvidia graphics packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - nvidia-libgl
      - nvidia
      - nvidia-settings

  # TODO: Somehow do this in X11 config only if this role is used?
  - name: install xorg configuration directory
    file:
      path: /etc/X11/xorg.conf.d
      state: directory
      mode: 0755

  - name: install xorg configuration file
    copy:
      src: 20-nvidia.conf
      dest: /etc/X11/xorg.conf.d/
      mode: 0644

  become: true

# Need to set metamodes at login instead of XORG conf due to bug in nvidia drivers
# See: https://devtalk.nvidia.com/default/topic/950647/linux/black-screen-with-367-35/
- name: install nvidia metamode set workaround
  copy:
    src: xprofile.d/nvidia-metamode-set-workaround
    dest: ~/.xprofile.d/
    mode: 0500
